version: '3.7'

services:
  fin_api-db:
    container_name: fin_api-db
    image: postgres:13.0
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=fin_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - TZ=GMT
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fin_api-network
  fin_api:
    container_name: fin_api
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - fin_api-db
    networks:
      - fin_api-network
networks:
  fin_api-network:
volumes:
  pgdata:
